server:
  port: 9876
  servlet:
    context-path: /miapp

spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.111:5432/base_de_datos
    username: matias
    password: matias
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
